/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra.view.user;

import hr.algebra.model.Channel;
import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.ChannelAddable;
import hr.algebra.model.ChannelArchive;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.ListSelectionModel;
import java.awt.datatransfer.Transferable;
import hr.algebra.model.ChannelTransferable;
import hr.algebra.utilities.JAXBUtils;
import hr.algebra.utilities.MessageUtils;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.SwingUtilities;
import javax.swing.TransferHandler;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.xml.bind.JAXBException;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatDarkLaf;


/**
 *
 * @author malesko
 */
public class UserForm extends javax.swing.JFrame implements ChannelAddable {

    private static final String FILENAME = "src/main/resources/xml/channelarchive.xml";

    private final Set<Channel> channels = new TreeSet<>();
    private final Set<Channel> favoriteChannels = new TreeSet<>();
    private final List<Channel> archive = new ArrayList<>();
    private final DefaultListModel<Channel> channelsModel = new DefaultListModel<>();
    private final DefaultListModel<Channel> favoriteChannelsModel = new DefaultListModel<>();
    
    private Channel selectedFavoriteChannel;
    private Repository repository;
    
    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
        initDragNDrop();
        handleThemes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsChannels = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsFavoriteChannels = new javax.swing.JList<>();
        btnRefresh = new javax.swing.JButton();
        btnSaveFavorites = new javax.swing.JButton();
        lbCHTitle = new javax.swing.JLabel();
        lbCHDate = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tpCHDescription = new javax.swing.JTextPane();
        btnLoadFavorites = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuView = new javax.swing.JMenu();
        menuTheme = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Channels");

        lsChannels.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lsChannelsFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(lsChannels);

        jLabel2.setText("Favorite Channels");

        lsFavoriteChannels.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lsFavoriteChannelsFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(lsFavoriteChannels);

        btnRefresh.setText("Refresh All");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSaveFavorites.setText("Save Favorites");
        btnSaveFavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFavoritesActionPerformed(evt);
            }
        });

        lbCHTitle.setText("Title");

        lbCHDate.setText("Date");

        jScrollPane4.setViewportView(tpCHDescription);

        btnLoadFavorites.setText("Load Favorites");
        btnLoadFavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFavoritesActionPerformed(evt);
            }
        });

        menuView.setMnemonic('V');
        menuView.setText("View");

        menuTheme.setMnemonic('T');
        menuTheme.setText("Theme");
        menuView.add(menuTheme);

        jMenuBar2.add(menuView);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCHDate, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLoadFavorites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSaveFavorites, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbCHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCHDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveFavorites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnLoadFavorites, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshModel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void btnSaveFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFavoritesActionPerformed
        try {
            JAXBUtils.save(new ChannelArchive(archive), FILENAME);
            MessageUtils.showInformationMessage("Info", "Channels saved.");
        } catch (JAXBException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveFavoritesActionPerformed

    private void lsChannelsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lsChannelsFocusLost
        lsChannels.clearSelection();
    }//GEN-LAST:event_lsChannelsFocusLost

    private void lsFavoriteChannelsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lsFavoriteChannelsFocusLost
        lsFavoriteChannels.clearSelection();
    }//GEN-LAST:event_lsFavoriteChannelsFocusLost

    private void btnLoadFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFavoritesActionPerformed
        try {
            ChannelArchive channelArchive = (ChannelArchive) JAXBUtils.load(ChannelArchive.class, FILENAME);
            archive.clear();
            archive.addAll(channelArchive.getChannels());
            favoriteChannels.clear();
            favoriteChannelsModel.clear();
            lsFavoriteChannels.clearSelection();
            archive.forEach(channel -> favoriteChannels.add(channel));
            loadFavoriteChannelsModel();
            MessageUtils.showInformationMessage("Info", "Loaded favorites");
        }
        catch (Exception e){
            MessageUtils.showErrorMessage("Error", "Unable to load favorites");
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_btnLoadFavoritesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadFavorites;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveFavorites;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbCHDate;
    private javax.swing.JLabel lbCHTitle;
    private javax.swing.JList<Channel> lsChannels;
    private javax.swing.JList<Channel> lsFavoriteChannels;
    private javax.swing.JMenu menuTheme;
    private javax.swing.JMenu menuView;
    private javax.swing.JTextPane tpCHDescription;
    // End of variables declaration//GEN-END:variables

    private void loadChannelsModel() {
        channelsModel.clear();
        channels.forEach(channelsModel::addElement);
        lsChannels.setModel(channelsModel);
    }

    private void loadChannelsFromDB() throws Exception {
        channels.clear();
        List<Channel> allchannels = repository.selectChannels();
        for (var channel : allchannels)
        {
            channels.add(channel);
        }
    }

    private void loadFavoriteChannelsModel() {
        favoriteChannelsModel.clear();
        favoriteChannels.forEach(favoriteChannelsModel::addElement);
        lsFavoriteChannels.setModel(favoriteChannelsModel);
    }

    private void initDragNDrop() {
        lsChannels.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsFavoriteChannels.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsChannels.setDragEnabled(true);
        lsChannels.setTransferHandler(new ExportTransferHandler());

        lsFavoriteChannels.setDropMode(DropMode.ON);
        lsFavoriteChannels.setTransferHandler(new ImportTransferHandler());
    }

    private void init() {
        try {
            repository = RepositoryFactory.getRepository();
            loadChannelsFromDB();
            loadFavoriteChannelsModel();
            loadChannelsModel();
            lsFavoriteChannels.addListSelectionListener((ListSelectionEvent e) -> {
                selectedFavoriteChannel = lsFavoriteChannels.getSelectedValue();
                loadChannelPreview();
                selectedFavoriteChannel = null;
            });
        }
        catch(Exception ex)
        {
            MessageUtils.showErrorMessage("Error", "Error loading channel(s)");
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refreshModel() {
        try {
            lsFavoriteChannels.clearSelection();
            favoriteChannels.clear();
            favoriteChannelsModel.clear();
            clearChannelPreview();
            loadChannelsFromDB();
            loadChannelsModel();
            loadFavoriteChannelsModel();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error refreshing", "Channel Model Error");
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearChannelPreview() {
        selectedFavoriteChannel = null;
        lsFavoriteChannels.clearSelection();
        lbCHTitle.setText("");
        tpCHDescription.setText("");
        lbCHDate.setText("");
    }
    
    private void loadChannelPreview() {
        if (selectedFavoriteChannel != null) {
            lbCHTitle.setText(selectedFavoriteChannel.getTitle());
            tpCHDescription.setText(selectedFavoriteChannel.getDescription());
            lbCHDate.setText(selectedFavoriteChannel.getPublishedDate().toString());
        }
    }

    @Override
    public boolean addChannel(Channel channel) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private class ExportTransferHandler extends TransferHandler {

        @Override
        public int getSourceActions(JComponent c) {
            return COPY;
        }

        @Override
        public Transferable createTransferable(JComponent c) {
            return new ChannelTransferable(lsChannels.getSelectedValue());
        }
    }

    
    private class ImportTransferHandler extends TransferHandler {

        @Override
        public boolean canImport(TransferSupport support) {
            return support.isDataFlavorSupported(ChannelTransferable.CHANNEL_FLAVOR);
        }

        @Override
        public boolean importData(TransferSupport support) {
            Transferable transferable = support.getTransferable();
            try {
                Channel add = (Channel) transferable.getTransferData(ChannelTransferable.CHANNEL_FLAVOR);
                if (favoriteChannels.add(add)) {
                    archive.add(add);
                    loadFavoriteChannelsModel();
                    return true;
                }
            } catch (UnsupportedFlavorException | IOException ex) {
                Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            return false;
        }
    }
    
     private void handleThemes() {
    ButtonGroup bgLookFeel = new ButtonGroup();


    JRadioButtonMenuItem miLight = new JRadioButtonMenuItem("Flat Light");
    bgLookFeel.add(miLight);
    menuTheme.add(miLight);
    miLight.addActionListener(e -> {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    });


    JRadioButtonMenuItem miDark = new JRadioButtonMenuItem("Flat Dark");
    bgLookFeel.add(miDark);
    menuTheme.add(miDark);
    miDark.addActionListener(e -> {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    });


    Arrays.asList(UIManager.getInstalledLookAndFeels()).forEach(lf -> {
        JRadioButtonMenuItem mi = new JRadioButtonMenuItem(lf.getName());
        bgLookFeel.add(mi);
        menuTheme.add(mi);
        if ("Nimbus".equals(lf.getName())) {
            mi.setSelected(true);
        }
        mi.addActionListener(e -> {
            try {
                UIManager.setLookAndFeel(lf.getClassName());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (Exception ex) {
                Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    });
}

    

}
