/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view.admin;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.view.admin.model.ChannelTableModel;
import hr.algebra.model.Channel;
import hr.algebra.utilities.FileUtils;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.utilities.IconUtils;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author malesko
 */
public class EditChannelPanel extends javax.swing.JPanel {

    private static final String DIR = "assets";

    private List<JLabel> errorLabels;
    private List<JTextComponent> validationFields;
    
    private Repository repository;
    private ChannelTableModel channelTableModel;
    
    private Channel selectedChannel;
    
    /**
     * Creates new form EditChannelPanel
     */
    public EditChannelPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCHImage = new javax.swing.JLabel();
        tfCHTitle = new javax.swing.JTextField();
        tfCHLink = new javax.swing.JTextField();
        tfCHPublishedDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCHDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbChannels = new javax.swing.JTable();
        btnUpdateChannel = new javax.swing.JButton();
        btnAddChannel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCHPicturePath = new javax.swing.JTextField();
        btnChooseImage = new javax.swing.JButton();
        lbCHTitleError = new javax.swing.JLabel();
        lbCHLinkError = new javax.swing.JLabel();
        lbCHDescriptionError = new javax.swing.JLabel();
        lbCHDateError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCHPicturePathError = new javax.swing.JLabel();
        btnDeleteChannel = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1570, 772));
        setMinimumSize(new java.awt.Dimension(1570, 772));
        setPreferredSize(new java.awt.Dimension(1280, 760));
        setVerifyInputWhenFocusTarget(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lbCHImage.setText("Channel image");

        taCHDescription.setColumns(20);
        taCHDescription.setRows(5);
        jScrollPane2.setViewportView(taCHDescription);

        tbChannels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbChannels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChannelsMouseClicked(evt);
            }
        });
        tbChannels.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbChannelsKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbChannels);

        btnUpdateChannel.setText("Update");
        btnUpdateChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateChannelActionPerformed(evt);
            }
        });

        btnAddChannel.setText("Add");
        btnAddChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChannelActionPerformed(evt);
            }
        });

        jLabel2.setText("Title");

        jLabel3.setText("Link");

        jLabel4.setText("Published Date");

        jLabel5.setText("Description");

        btnChooseImage.setText("Choose");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });

        lbCHTitleError.setForeground(new java.awt.Color(255, 102, 102));
        lbCHTitleError.setText("X");

        lbCHLinkError.setForeground(new java.awt.Color(255, 102, 102));
        lbCHLinkError.setText("X");

        lbCHDescriptionError.setForeground(new java.awt.Color(255, 102, 102));
        lbCHDescriptionError.setText("X");

        lbCHDateError.setForeground(new java.awt.Color(255, 102, 102));
        lbCHDateError.setText("X");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Item information");

        lbCHPicturePathError.setForeground(new java.awt.Color(255, 102, 102));
        lbCHPicturePathError.setText("X");

        btnDeleteChannel.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteChannel.setText("DELETE");
        btnDeleteChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteChannelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnDeleteChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfCHTitle)
                                    .addComponent(tfCHLink, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCHTitleError)
                                    .addComponent(lbCHLinkError)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCHDescriptionError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(lbCHDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfCHPublishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(tfCHPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChooseImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCHPicturePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbCHImage, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbCHImage, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCHPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChooseImage)
                            .addComponent(lbCHPicturePathError)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCHTitleError))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lbCHDateError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCHLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCHPublishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCHLinkError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbCHDescriptionError))
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateChannel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDeleteChannel)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChannelActionPerformed
        // TODO add your handling code here:
        if (!formValid()) {
            return;
        }
        try {
            String localPicturePath = uploadPicture();
            Channel channel = new Channel(
                    tfCHTitle.getText().trim(),
                    tfCHLink.getText().trim(),
                    taCHDescription.getText().trim(),
                    localPicturePath,
                    LocalDateTime.parse(tfCHPublishedDate.getText().trim(), Channel.DATE_FORMATTER)
            );
            repository.createChannel(channel);
            channelTableModel.setChannels(repository.selectChannels());
            clearForm();
            MessageUtils.showInformationMessage("Success", "Channel added");
        } catch (Exception ex) {
            Logger.getLogger(EditChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to create article!");
        }
    }//GEN-LAST:event_btnAddChannelActionPerformed

    private void btnUpdateChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateChannelActionPerformed
        // TODO add your handling code here:
        if (selectedChannel == null) {
            MessageUtils.showInformationMessage("Wrong operation", "Please choose article to update");
            return;
        }
        if (!formValid()) {
            return;
        }
        try {
            if (!tfCHPicturePath.getText().trim().equals(selectedChannel.getPicturePath())) {
                if (selectedChannel.getPicturePath() != null) {
                    Files.deleteIfExists(Paths.get(selectedChannel.getPicturePath()));
                }
                String localPicturePath = uploadPicture();
                selectedChannel.setPicturePath(localPicturePath);
            }

            selectedChannel.setTitle(tfCHTitle.getText().trim());
            selectedChannel.setLink(tfCHLink.getText().trim());
            selectedChannel.setDescription(taCHDescription.getText().trim());
            selectedChannel.setPublishedDate(LocalDateTime.parse(tfCHPublishedDate.getText().trim(), Channel.DATE_FORMATTER));

            repository.updateChannel(selectedChannel.getId(), selectedChannel);
            channelTableModel.setChannels(repository.selectChannels());
            clearForm();
            MessageUtils.showInformationMessage("Success", "Channel updated");
        } catch (Exception ex) {
            Logger.getLogger(EditChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to update article!");
        }

    }//GEN-LAST:event_btnUpdateChannelActionPerformed

    private void btnDeleteChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteChannelActionPerformed
        // TODO add your handling code here:
        if (selectedChannel == null) {
            MessageUtils.showInformationMessage("Wrong operation", "Please choose article to delete");
            return;
        }
        if (MessageUtils.showConfirmDialog(
                "Delete article",
                "Do you really want to delete article?")) {
            try {
                if (selectedChannel.getPicturePath() != null) {
                    Files.deleteIfExists(Paths.get(selectedChannel.getPicturePath()));
                }
                repository.deleteChannel(selectedChannel.getId());
                channelTableModel.setChannels(repository.selectChannels());
                clearForm();
                MessageUtils.showInformationMessage("Success", "Channel deleted");
            } catch (Exception ex) {
                Logger.getLogger(EditChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage("Error", "Unable to delete article!");
            }
        }
    }//GEN-LAST:event_btnDeleteChannelActionPerformed

    private void tbChannelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChannelsMouseClicked
        // TODO add your handling code here:
        showChannel();
    }//GEN-LAST:event_tbChannelsMouseClicked

    private void tbChannelsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbChannelsKeyReleased
        // TODO add your handling code here:
        showChannel();
    }//GEN-LAST:event_tbChannelsKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        init();
    }//GEN-LAST:event_formComponentShown

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        // TODO add your handling code here:
        Optional<File> opt = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");
        if (opt.isEmpty()) {
            return;
        }
        tfCHPicturePath.setText(opt.get().getAbsolutePath());
        setIcon(lbCHImage, opt.get());
    }//GEN-LAST:event_btnChooseImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddChannel;
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnDeleteChannel;
    private javax.swing.JButton btnUpdateChannel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCHDateError;
    private javax.swing.JLabel lbCHDescriptionError;
    private javax.swing.JLabel lbCHImage;
    private javax.swing.JLabel lbCHLinkError;
    private javax.swing.JLabel lbCHPicturePathError;
    private javax.swing.JLabel lbCHTitleError;
    private javax.swing.JTextArea taCHDescription;
    private javax.swing.JTable tbChannels;
    private javax.swing.JTextField tfCHLink;
    private javax.swing.JTextField tfCHPicturePath;
    private javax.swing.JTextField tfCHPublishedDate;
    private javax.swing.JTextField tfCHTitle;
    // End of variables declaration//GEN-END:variables

    private void init() {
        try {
            initValidation();
            hideErrors();
            initRepository();
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(EditChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    
    private void initValidation() {
        validationFields = Arrays.asList(tfCHTitle, tfCHLink, taCHDescription, tfCHPublishedDate, tfCHPicturePath);
        errorLabels = Arrays.asList(lbCHTitleError, lbCHLinkError, lbCHDescriptionError, lbCHDateError, lbCHPicturePathError);
    }
    
    private void hideErrors()
    {
        errorLabels.forEach(e -> e.setVisible(false));
    }
    
    private void initRepository() throws Exception {
        repository = RepositoryFactory.getRepository();
    }

    private void initTable() throws Exception {
        tbChannels.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbChannels.setAutoCreateRowSorter(true);
        tbChannels.setRowHeight(25);
        channelTableModel = new ChannelTableModel(repository.selectChannels());
        tbChannels.setModel(channelTableModel);
    }
 
    
    private boolean formValid() {
        hideErrors();
        boolean ok = true;

        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setVisible(validationFields.get(i).getText().trim().isEmpty());
            if ("Date".equals(validationFields.get(i).getName())) {
                try {
                    LocalDateTime.parse(validationFields.get(i).getText().trim(), Channel.DATE_FORMATTER);
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setVisible(true);
                }
            }
        }
        return ok;
    }

    
    private void clearForm() {
        hideErrors();
        validationFields.forEach(e -> e.setText(""));
        lbCHImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no_image.png")));
        selectedChannel = null;
    }

    private String uploadPicture() throws IOException {
        String picturePath = tfCHPicturePath.getText();
        String ext = picturePath.substring(picturePath.lastIndexOf("."));
        String pictureName = UUID.randomUUID() + ext;
        String localPicturePath = DIR + File.separator + pictureName;

        FileUtils.copy(picturePath, localPicturePath);
        return localPicturePath;
    }
    
    private void showChannel() {
        clearForm();
        int selectedRow = tbChannels.getSelectedRow();
        int rowIndex = tbChannels.convertRowIndexToModel(selectedRow);
        int selectedChannelId = (int) channelTableModel.getValueAt(rowIndex, 0);

        try {
            Optional<Channel> optArticle = repository.selectChannel(selectedChannelId);
            if (optArticle.isPresent()) {
                selectedChannel = optArticle.get();
                fillForm(selectedChannel);
            }
        } catch (Exception ex) {
            Logger.getLogger(EditChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to show article!");
        }
    }
    
    private void fillForm(Channel channel) {
        if (channel.getPicturePath() != null && Files.exists(Paths.get(channel.getPicturePath()))) {
            tfCHPicturePath.setText(channel.getPicturePath());
            setIcon(lbCHImage, new File(channel.getPicturePath()));
        }
        tfCHTitle.setText(channel.getTitle());
        tfCHLink.setText(channel.getLink());
        taCHDescription.setText(channel.getDescription());
        tfCHPublishedDate.setText(channel.getPublishedDate().format(Channel.DATE_FORMATTER));
    }
    
    private void setIcon(JLabel label, File file) {
        try {
            label.setIcon(IconUtils.createIcon(file, label.getWidth(), label.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(EditChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to set icon!");
        }
    }
    
}
