/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view.admin;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Channel;
import hr.algebra.rss.ChannelRssParser;
import hr.algebra.utilities.MessageUtils;
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author malesko
 */
public class UploadChannelPanel extends javax.swing.JPanel {

    
    private List<Channel> channels = new ArrayList<>();
    
    /**
     * Creates new form UploadChannelPanel
     */
    public UploadChannelPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsChannels = new javax.swing.JList<>();
        btnUploadChannels = new javax.swing.JButton();
        cbCHExtension = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1570, 772));
        setMinimumSize(new java.awt.Dimension(1570, 772));
        setPreferredSize(new java.awt.Dimension(1570, 772));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setViewportView(lsChannels);

        btnUploadChannels.setText("Upload Channels");
        btnUploadChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadChannelsActionPerformed(evt);
            }
        });

        cbCHExtension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "UK", "World", "US", "Business", "Politics", "Technology", "Entertainment", "Strange" }));

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btnDelete.setText("DELETE ALL");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnUploadChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cbCHExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCHExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadChannelsActionPerformed
        new Thread(() -> {
            ext = cbCHExtension.getSelectedItem().toString().toLowerCase();
            try {
                channels.addAll(ChannelRssParser.parseChannelItems(ext));
                repository.createChannels(channels);
                loadModel();

            } catch (Exception ex) {
                MessageUtils.showErrorMessage("Unrecoverable error", "Unable to upload articles");
                System.exit(1);
            }}).start();
        
    }//GEN-LAST:event_btnUploadChannelsActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        init();
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            channels.clear();
            repository.deleteChannels();
            loadModel();
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Error", "Error loading model");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUploadChannels;
    private javax.swing.JComboBox<String> cbCHExtension;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Channel> lsChannels;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel<Channel> channelModel;
    private Repository repository;
    private String ext;
    
    private void init() {
        try {
            repository = RepositoryFactory.getRepository();
            channelModel = new DefaultListModel<>();
            loadModel();
        } catch (Exception ex) {
            Logger.getLogger(UploadChannelPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }
    
    private void loadModel() throws Exception {
        channels = repository.selectChannels();
        
        EventQueue.invokeLater(() -> {    
            channelModel.clear();
            channels.forEach(channelModel::addElement);
            lsChannels.setModel(channelModel);
        });
    }


}
